  version: '3.5'
  services:
    web:
      build: .
      image: node-server
      ports:
      - "3000:3000"
      networks:
      - network1
      depends_on:
      - mongodb
    mongodb:
      image: mongo
      restart: always
      ports:
      - "27017:27017"
      networks:
        network1:
          aliases:
          - db
      volumes:
      - "/var/node-server/db:/data/db"


  networks:
    network1:
      driver: bridge
      name: node-server-network
