version: '3.5'
services:
  web:
    build: .
    image: node-server
    restart: on-failure
    ports:
      - "8089:3000"
    networks:
      - frontend
    depends_on:
      - mongodbserver
    env_file: .env

  mongodb:
    image: mongo
    restart: always
    ports:
      - "37017:27017"
    networks:
      - frontend
    volumes:
      - "dbdata:/data/db"

networks:
  frontend:
    driver: bridge
volumes:
  dbdata: